In [2]:
import geopandas as gpd

shapefile_path = '..\..\BR_Municipios_2024\BR_Municipios_2024.shp'

# Carrega o shapefile usando geopandas
gdf_municipios = gpd.read_file(shapefile_path)

shapefile_path = '..\..\BR_UF_2024\BR_UF_2024.shp'

# Carrega o shapefile usando geopandas
gdf_estados = gpd.read_file(shapefile_path)

In [3]:
gdf_municipios.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 5573 entries, 0 to 5572
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CD_MUN    5573 non-null   object
 1   NM_MUN    5573 non-null   object
 2   CD_RGI    5571 non-null   object
 3   NM_RGI    5571 non-null   object
 4   CD_RGINT  5571 non-null   object
 5   NM_RGINT  5571 non-null   object
 6   CD_UF     5573 non-null   object
 7   NM_UF     5573 non-null   object
 8   SIGLA_UF  5573 non-null   object
 9   CD_REGIA  5573 non-null   object
 10  NM_REGIA  5573 non-null   object
 11  SIGLA_RG  5573 non-null   object
 12  CD_CONCU  660 non-null    object
 13  NM_CONCU  660 non-null    object
 14  AREA_KM2  5573 non-null   float64
 15  geometry  5573 non-null   geometry
dtypes: float64(1), geometry(1), object(14)
memory usage: 696.8+ KB

In [4]:
col = ['CD_MUN',
    'NM_MUN',
    'CD_UF',
    'NM_UF',
    'SIGLA_UF',
    'CD_REGIA',
    'NM_REGIA',
    'AREA_KM2',
    'geometry']

gdf_municipios = gdf_municipios[col]
gdf_municipios = gdf_municipios.rename(columns={'geometry': 'POLYGON'})    

gdf_municipios.head()

,CD_MUN,NM_MUN,CD_UF,NM_UF,SIGLA_UF,CD_REGIA,NM_REGIA,AREA_KM2,POLYGON
0,2504108,Carrapateira,25,Paraíba,PB,2,Nordeste,59.070,"POLYGON ((-38.33672 -6.99279, -38.33653 -6.993..."
1,1718451,Pugmil,17,Tocantins,TO,1,Norte,401.174,"POLYGON ((-48.91085 -10.53824, -48.911 -10.538..."
2,2104206,Fortuna,21,Maranhão,MA,2,Nordeste,835.668,"POLYGON ((-43.95962 -5.49793, -43.96181 -5.497..."
3,5219902,São Francisco de Goiás,52,Goiás,GO,5,Centro-oeste,416.535,"POLYGON ((-49.29477 -16.00852, -49.29484 -16.0..."
4,2708600,São Miguel dos Campos,27,Alagoas,AL,2,Nordeste,335.679,"POLYGON ((-36.0739 -9.70094, -36.07339 -9.7008..."

In [5]:
gdf_estados = gdf_estados.rename(columns={'geometry': 'POLYGON'})  

gdf_estados.head()

,CD_UF,NM_UF,SIGLA_UF,CD_REGIA,NM_REGIA,SIGLA_RG,AREA_KM2,POLYGON
0,35,São Paulo,SP,3,Sudeste,SE,248219.485,"MULTIPOLYGON (((-48.03541 -25.35682, -48.0355 ..."
1,15,Pará,PA,1,Norte,N,1245828.829,"MULTIPOLYGON (((-50.84599 -9.80064, -51.05801 ..."
2,32,Espírito Santo,ES,3,Sudeste,SE,46074.448,"MULTIPOLYGON (((-40.88336 -21.16372, -40.88345..."
3,12,Acre,AC,1,Norte,N,164082.960,"POLYGON ((-68.39021 -11.04496, -68.39073 -11.0..."
4,13,Amazonas,AM,1,Norte,N,1558706.127,"POLYGON ((-67.51732 -9.56071, -67.51776 -9.560..."

In [6]:
gdf_municipios.to_csv('..\datasets\gdf_municipios.csv', index=False)
gdf_estados.to_csv('..\datasets\gdf_estados.csv', index=False)

In [6]:
merged_gdf = gdf_municipios.merge(gdf_estados, left_on='CD_UF', right_on='CD_UF', suffixes=('_municipio', '_estado'))

merged_gdf.head()

,CD_MUN,NM_MUN,CD_UF,NM_UF_municipio,SIGLA_UF_municipio,CD_REGIA_municipio,NM_REGIA_municipio,AREA_KM2_municipio,geom_municipio,NM_UF_estado,SIGLA_UF_estado,CD_REGIA_estado,NM_REGIA_estado,SIGLA_RG,AREA_KM2_estado,geom_estado
0,2504108,Carrapateira,25,Paraíba,PB,2,Nordeste,59.070,"POLYGON ((-38.33672 -6.99279, -38.33653 -6.993...",Paraíba,PB,2,Nordeste,NE,56467.242,"MULTIPOLYGON (((-34.798 -7.36278, -34.79794 -7..."
1,1718451,Pugmil,17,Tocantins,TO,1,Norte,401.174,"POLYGON ((-48.91085 -10.53824, -48.911 -10.538...",Tocantins,TO,1,Norte,N,277423.627,"POLYGON ((-49.90935 -12.97449, -49.90936 -12.9..."
2,2104206,Fortuna,21,Maranhão,MA,2,Nordeste,835.668,"POLYGON ((-43.95962 -5.49793, -43.96181 -5.497...",Maranhão,MA,2,Nordeste,NE,329651.478,"MULTIPOLYGON (((-45.86986 -10.07488, -45.87149..."
3,5219902,São Francisco de Goiás,52,Goiás,GO,5,Centro-oeste,416.535,"POLYGON ((-49.29477 -16.00852, -49.29484 -16.0...",Goiás,GO,5,Centro-oeste,CO,340242.860,"POLYGON ((-50.5003 -18.92972, -50.50157 -18.93..."
4,2708600,São Miguel dos Campos,27,Alagoas,AL,2,Nordeste,335.679,"POLYGON ((-36.0739 -9.70094, -36.07339 -9.7008...",Alagoas,AL,2,Nordeste,NE,27830.661,"MULTIPOLYGON (((-35.76043 -9.69489, -35.76044 ..."